export { setAttribute, addRemoveAttr, wcClass, wcClassObject } from './attr'
export { EventName } from './events'
export { setInputCaret, isAutoFilled, isFocused, getInvalidMessage, getValue } from './inputs'
export { replaceElementContents, setOptions, setStyleRules } from './markup'
export { findIn } from './query'
export { svgTags, htmlTags } from './tags'