module.exports = {
    accentcolor: process.env.INPUTFIELD_ACCENTCOLOR || process.env.ACCENT_COLOR || `#59a2d8`,
    accept: process.env.INPUTFIELD_ACCEPT || null,
    allowhtml: process.env.INPUTFIELD_ALLOWHTML || null,
    autocomplete: process.env.INPUTFIELD_AUTOCOMPLETE || null,
    autofocus: process.env.INPUTFIELD_AUTOFOCUS || null,
    checkIcon: process.env.INPUTFIELD_CHECKICON || process.env.CHECKICON || `<svg xmlns="http://www.w3.org/2000/svg" style="stroke:currentColor;stroke-width:2px;" width="24" height="24" viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>`,
    clearbutton: process.env.INPUTFIELD_CLEARBUTTON || null,
    count: process.env.INPUTFIELD_COUNT || 0,
    disabled: process.env.INPUTFIELD_DISABLED || null,
    disallowhtml: process.env.INPUTFIELD_DISALLOWHTML || null,
    emptyoption: process.env.INPUTFIELD_EMPTYOPTION || `Select...`,
    errortext: process.env.INPUTFIELD_ERRORTEXT || ``,
    format: process.env.INPUTFIELD_FORMAT || null,
    helptext: process.env.INPUTFIELD_HELPTEXT || ``,
    icon: process.env.INPUTFIELD_ICON || null,
    label: process.env.INPUTFIELD_LABEL || ``,
    max: process.env.INPUTFIELD_MAX || null,
    maxlength: process.env.INPUTFIELD_MAXLENGTH || null,
    min: process.env.INPUTFIELD_MIN || null,
    name: process.env.INPUTFIELD_NAME || null,
    pattern: process.env.INPUTFIELD_PATTERN || null,
    placeholder: process.env.INPUTFIELD_PLACEHOLDER || null,
    resize: process.env.INPUTFIELD_RESIZE || `auto`,
    step: process.env.INPUTFIELD_STEP || null,
    styles: process.env.INPUTFIELD_STYLES || ``,
    tabindex: process.env.INPUTFIELD_TABINDEX || null,
    type: process.env.INPUTFIELD_TYPE || `text`,
    warningcolor: process.env.INPUTFIELD_WARNINGCOLOR || process.env.WARNING_COLOR || `#a10005`,

    // SASS VARS
    sass: {
        inputfield_accentcolor: process.env.INPUTFIELD_ACCENTCOLOR || process.env.ACCENT_COLOR || `#59a2d8`,
        inputfield_warningcolor: process.env.INPUTFIELD_WARNINGCOLOR || process.env.WARNING_COLOR || `#a10005`,
        inputfield_width: process.env.INPUTFIELD_WIDTH || `300px`,
        inputfield_backgroundColor: process.env.INPUTFIELD_BACKGROUNDCOLOR || process.env.PRIMARY_BACKGROUND_COLOR || `rgba(255, 255, 255, .4)`,
        inputfield_backgroundColorDisabled: process.env.INPUTFIELD_BACKGROUNDCOLORDISABLED || process.env.PRIMARY_BACKGROUND_COLOR || `rgba(200, 200, 200, 0.6)`,
        inputfield_borderRadius: process.env.INPUTFIELD_BORDER_RADIUS || process.env.BORDER_RADIUS || `2px`,
        inputfield_checkColor: process.env.INPUTFIELD_CHECKCOLOR || process.env.ACCENT_OFFSET_COLOR || `#fff`,
        inputfield_disabledOpacity: process.env.INPUTFIELD_DISABLEDOPACITY || `0.6`,
        inputfield_invalidShadowColor: process.env.INPUTFIELD_INVALIDSHADOWCOLOR || process.env.WARNING_COLOR || `#a10005`,
        inputfield_invalidShadow: process.env.INPUTFIELD_INVALIDSHADOW || `inset 0px 0px 0px 1px ${process.env.INPUTFIELD_INVALIDSHADOWCOLOR || process.env.WARNING_COLOR || `#a10005`}`,
        inputfield_labelWeight: process.env.INPUTFIELD_LABELWEIGHT || `bold`,
        inputfield_optionColor: process.env.INPUTFIELD_OPTIONCOLOR || process.env.PRIMARY_COLOR || `#333`,
        inputfield_optionBackgroundColor: process.env.INPUTFIELD_OPTIONBACKGROUNDCOLOR || process.env.PRIMARY_BACKGROUND_COLOR || `#fafafa`,
        inputfield_optionHoverColor: process.env.INPUTFIELD_OPTIONHOVERCOLOR || process.env.ACCENT_OFFSET_COLOR || `#fff`,
        inputfield_optionHoverBackgroundColor: process.env.INPUTFIELD_OPTIONHOVERBACKGROUNDCOLOR || process.env.INPUTFIELD_ACCENTCOLOR || process.env.ACCENT_COLOR || `#59a2d8`,
        inputfield_optionActiveColor: process.env.INPUTFIELD_OPTIONACTIVECOLOR || process.env.ACCENT_OFFSET_COLOR || `#fff`,
        inputfield_optionActiveBackgroundColor: process.env.INPUTFIELD_OPTIONACTIVEBACKGROUNDCOLOR || process.env.INPUTFIELD_ACCENTCOLOR || process.env.ACCENT_COLOR || `#59a2d8`,
        inputfield_shadowColor: process.env.INPUTFIELD_SHADOWCOLOR || `rgba(0, 0, 0, .31)`,
        inputfield_shadow: process.env.INPUTFIELD_SHADOW || `inset 0px 0px 0px 1px ${process.env.INPUTFIELD_SHADOWCOLOR || ``}`,
    }
}